import { useCallback, useEffect, useState } from 'react'
import { Activity, BarChart3, Bell, CreditCard, LayoutDashboard, LogOut, Menu, PauseCircle, PlayCircle, Settings, ShieldCheck, SlidersHorizontal, Trash2, Users, X } from 'lucide-react'
import { adminApi, type AdminOverview, type AdminUser } from '../services/admin.api'
import '../styles/admin.css'

const SESSION_KEY = 'careertide-admin-session'
type Section = 'overview' | 'users' | 'runs' | 'payments' | 'notifications' | 'settings'

const nav = [{ id: 'overview', label: 'Overview', Icon: LayoutDashboard }, { id: 'users', label: 'Candidates', Icon: Users }, { id: 'runs', label: 'Job runs', Icon: Activity }, { id: 'payments', label: 'Payments', Icon: CreditCard }, { id: 'notifications', label: 'Email logs', Icon: Bell }, { id: 'settings', label: 'Settings', Icon: Settings }] as const
const num = (value?: string) => Number(value ?? 0).toLocaleString('en-IN')

export function AdminPage() {
  const [token, setToken] = useState(() => sessionStorage.getItem(SESSION_KEY) ?? '')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  const [overview, setOverview] = useState<AdminOverview | null>(null)
  const [users, setUsers] = useState<AdminUser[]>([])
  const [section, setSection] = useState<Section>('overview')
  const [menuOpen, setMenuOpen] = useState(false)
  const [selectedUser, setSelectedUser] = useState<AdminUser | null>(null)

  const load = useCallback(async () => {
    if (!token) return
    setLoading(true)
    try {
      const [overviewData, usersData] = await Promise.all([adminApi.overview(token), adminApi.users(token)])
      setOverview(overviewData); setUsers(usersData.users); setError('')
    } catch (requestError) {
      const message = requestError instanceof Error ? requestError.message : 'Could not load the admin dashboard.'
      setError(message)
      if (/session|sign-in|401/i.test(message)) { sessionStorage.removeItem(SESSION_KEY); setToken('') }
    } finally { setLoading(false) }
  }, [token])
  useEffect(() => {
    if (!token) return
    const loadTimer = window.setTimeout(() => { void load() }, 0)
    return () => window.clearTimeout(loadTimer)
  }, [load, token])
  const login = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const result = await adminApi.login(email, password); sessionStorage.setItem(SESSION_KEY, result.token); setToken(result.token); setPassword('') } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Sign-in failed.') } finally { setLoading(false) } }
  const logout = async () => { try { await adminApi.logout(token) } finally { sessionStorage.removeItem(SESSION_KEY); setToken(''); setOverview(null) } }
  const updateWorkflow = async (user: AdminUser) => { const next = user.workflow_status === 'active' ? 'paused' : 'active'; await adminApi.updateWorkflow(token, user.id, next); await load() }
  const saveRules = async (user: AdminUser, rules: { schedule: string; timezone: string; dailyLimit: number; minimumScore: number; locations: string }) => { await adminApi.updateRules(token, user.id, rules); setSelectedUser(null); await load() }
  const deleteUser = async (user: AdminUser) => { if (!window.confirm(`Delete ${user.full_name} and all of their CareerTide data? This cannot be undone.`)) return; await adminApi.deleteUser(token, user.id); setSelectedUser(null); await load() }

  if (!token) return <main className="admin-login"><section><div className="admin-login-brand"><ShieldCheck /> <span>Career<span>Tide</span> Admin</span></div><small>CONTROL CENTER</small><h1>Run your career platform with clarity.</h1><p>Secure access to candidates, job runs, platform activity, payments, and operational controls.</p><form onSubmit={login}><label>Admin email<input value={email} type="email" onChange={(event) => setEmail(event.target.value)} placeholder="admin@careertide.com" required /></label><label>Password<input value={password} type="password" onChange={(event) => setPassword(event.target.value)} placeholder="Enter your password" required /></label>{error && <div className="admin-error">{error}</div>}<button disabled={loading}>{loading ? 'Checking access…' : 'Sign in to Admin'}</button></form><small className="admin-login-note">Credentials are configured through secure server environment variables.</small></section></main>

  return <main className="admin-shell"><aside className={menuOpen ? 'open' : ''}><div className="admin-brand"><ShieldCheck /><strong>Career<span>Tide</span></strong><small>ADMIN</small><button className="admin-drawer-close" onClick={() => setMenuOpen(false)} aria-label="Close admin menu"><X /></button></div><nav>{nav.map(({ id, label, Icon }) => <button className={section === id ? 'active' : ''} key={id} onClick={() => { setSection(id); setMenuOpen(false) }}><Icon />{label}</button>)}</nav><div className="admin-user"><span>Platform administrator</span><button onClick={() => void logout()}><LogOut /> Sign out</button></div></aside><div className="admin-main"><header><button className="admin-menu" onClick={() => setMenuOpen(true)} aria-label="Open admin menu"><Menu /></button><div><small>ADMIN / {section.toUpperCase()}</small><h1>{nav.find((item) => item.id === section)?.label}</h1></div><button className="admin-refresh" onClick={() => void load()}><Activity /> {loading ? 'Refreshing' : 'Live data'}</button></header>{error && <div className="admin-error">{error}</div>}{overview && <AdminContent section={section} overview={overview} users={users} onWorkflow={updateWorkflow} onManage={setSelectedUser} />}</div><nav className="admin-mobile-shortcuts" aria-label="Admin shortcuts">{nav.slice(0, 4).map(({ id, label, Icon }) => <button key={id} className={section === id ? 'active' : ''} onClick={() => setSection(id)}><Icon /><span>{label}</span></button>)}<button onClick={() => setMenuOpen(true)}><Menu /><span>More</span></button></nav>{selectedUser && <CandidateManager user={selectedUser} onClose={() => setSelectedUser(null)} onSave={saveRules} onDelete={deleteUser} />}</main>
}

function AdminContent({ section, overview, users, onWorkflow, onManage }: { section: Section; overview: AdminOverview; users: AdminUser[]; onWorkflow: (user: AdminUser) => Promise<void>; onManage: (user: AdminUser) => void }) {
  if (section === 'users') return <section className="admin-content"><Panel title="Candidate directory" subtitle="Profiles, preferences, and workflow controls"><CandidateTable users={users} onWorkflow={onWorkflow} onManage={onManage} /></Panel></section>
  if (section === 'runs') return <section className="admin-content"><Panel title="Recent job runs" subtitle="Genuine PostgreSQL-backed job-search activity"><RunList runs={overview.recentRuns} /></Panel></section>
  if (section === 'payments') return <section className="admin-content"><StatGrid overview={overview} /><Panel title="Payment operations" subtitle="Verified activation deposits are recorded in PostgreSQL."><div className="admin-empty">₹{num(overview.payments.amount)} across {num(overview.payments.verified)} verified payment records.</div></Panel></section>
  if (section === 'notifications') return <section className="admin-content"><StatGrid overview={overview} /><Panel title="Admin activity" subtitle="Security and operational audit events"><AuditList audits={overview.audits} /></Panel></section>
  if (section === 'settings') return <section className="admin-content"><Panel title="Platform settings" subtitle="Secure values stay in server environment variables."><div className="admin-settings-grid"><div><ShieldCheck /><strong>Admin access</strong><span>Set ADMIN_EMAIL and ADMIN_PASSWORD in the server/Vercel environment.</span></div><div><Bell /><strong>Delivery</strong><span>Configure SMTP values for transactional notifications.</span></div><div><CreditCard /><strong>Payments</strong><span>Configure Razorpay Test or Live keys in server environment variables.</span></div></div></Panel></section>
  return <section className="admin-content"><StatGrid overview={overview} /><div className="admin-layout"><Panel title="Candidate activity" subtitle="Latest onboarding and workflow status"><CandidateTable users={users.slice(0, 5)} onWorkflow={onWorkflow} onManage={onManage} /></Panel><Panel title="Recent search runs" subtitle="Live database activity"><RunList runs={overview.recentRuns.slice(0, 5)} /></Panel></div><div className="admin-layout"><Panel title="Source adoption" subtitle="Selected and active source workflows"><SourceSignals sources={overview.sources} /></Panel><Panel title="Candidate demand signals" subtitle="Most requested roles from candidate profiles"><TrendSignals trends={overview.trends} /></Panel></div><Panel title="Administrative audit trail" subtitle="Recent protected admin actions"><AuditList audits={overview.audits} /></Panel></section>
}

function StatGrid({ overview }: { overview: AdminOverview }) { const items = [{ label: 'Registered candidates', value: num(overview.totals.users), note: `${num(overview.totals.profiles)} profiles ready`, Icon: Users }, { label: 'Active workflows', value: num(overview.workflows.active), note: `${num(overview.workflows.paused)} paused`, Icon: Activity }, { label: 'Verified payments', value: num(overview.payments.verified), note: `₹${num(overview.payments.amount)} recorded`, Icon: CreditCard }, { label: 'Email delivery', value: num(overview.emails.sent), note: `${num(overview.emails.failed)} failed`, Icon: Bell }]; return <div className="admin-stats">{items.map(({ label, value, note, Icon }) => <article key={label}><span><Icon /></span><small>{label}</small><strong>{value}</strong><em>{note}</em></article>)}</div> }
function Panel({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <article className="admin-panel"><header><div><h2>{title}</h2><p>{subtitle}</p></div><BarChart3 /></header>{children}</article> }
function CandidateTable({ users, onWorkflow, onManage }: { users: AdminUser[]; onWorkflow: (user: AdminUser) => Promise<void>; onManage: (user: AdminUser) => void }) { return <div className="admin-table-wrap"><table><thead><tr><th>Candidate</th><th>Profile</th><th>Matches</th><th>Workflow</th><th>Control</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><strong>{user.full_name}</strong><small>{user.email}</small></td><td>{user.roles || 'Profile pending'}<small>{user.experience || '—'} · {user.locations || '—'}</small></td><td>{user.matches}</td><td><span className={`admin-status ${user.workflow_status}`}>{user.workflow_status}</span></td><td><div className="admin-user-actions">{['active', 'paused'].includes(user.workflow_status) && <button className="workflow-control" onClick={() => void onWorkflow(user)}>{user.workflow_status === 'active' ? <><PauseCircle /> Pause</> : <><PlayCircle /> Activate</>}</button>}<button className="workflow-control" onClick={() => onManage(user)}><SlidersHorizontal /> Manage</button></div></td></tr>)}{!users.length && <tr><td colSpan={5}>No candidates have completed profile setup yet.</td></tr>}</tbody></table></div> }
function RunList({ runs }: { runs: AdminOverview['recentRuns'] }) { const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const visibleRuns = runs.filter((run) => { const date = run.started_at.slice(0, 10); return (!from || date >= from) && (!to || date <= to) }); return <><div className="admin-run-filter"><label>From<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label>To<input type="date" value={to} min={from || undefined} onChange={(event) => setTo(event.target.value)} /></label></div><div className="admin-run-list">{visibleRuns.map((run) => <div key={run.id}><span className={run.status}><Activity /></span><div><strong>{run.full_name}</strong><small>{new Date(run.started_at).toLocaleString()} · {run.jobs_discovered} checked · {run.jobs_matched} matched</small></div><em>{run.status}</em></div>)}{!visibleRuns.length && <div className="admin-empty">No job runs found for this date range.</div>}</div></> }
function AuditList({ audits }: { audits: AdminOverview['audits'] }) { return <div className="admin-audit">{audits.map((audit, index) => <div key={`${audit.created_at}-${index}`}><i /><span><strong>{audit.action.replaceAll('_', ' ')}</strong><small>{audit.admin_email} · {new Date(audit.created_at).toLocaleString()}</small></span></div>)}{!audits.length && <div className="admin-empty">No admin actions recorded yet.</div>}</div> }
function SourceSignals({ sources }: { sources: AdminOverview['sources'] }) { return <div className="admin-signals">{sources.map((source) => <div key={source.source}><span><strong>{source.source}</strong><small>{num(source.candidates)} candidates · {num(source.active)} active</small></span><b>{num(source.candidates)}</b></div>)}{!sources.length && <div className="admin-empty">No job source has been selected yet.</div>}</div> }
function TrendSignals({ trends }: { trends: AdminOverview['trends'] }) { return <div className="admin-signals">{trends.map((trend, index) => <div key={trend.label}><span><strong>{index + 1}. {trend.label}</strong><small>Requested by {num(trend.candidates)} candidate{Number(trend.candidates) === 1 ? '' : 's'}</small></span><b>{num(trend.candidates)}</b></div>)}{!trends.length && <div className="admin-empty">Role trend data appears after candidates save their profile.</div>}</div> }

function CandidateManager({ user, onClose, onSave, onDelete }: { user: AdminUser; onClose: () => void; onSave: (user: AdminUser, rules: { schedule: string; timezone: string; dailyLimit: number; minimumScore: number; locations: string }) => Promise<void>; onDelete: (user: AdminUser) => Promise<void> }) {
  const [schedule, setSchedule] = useState(user.schedule ?? '09:00'); const [timezone, setTimezone] = useState(user.timezone ?? 'Asia/Kolkata'); const [dailyLimit, setDailyLimit] = useState(user.daily_limit ?? 10); const [minimumScore, setMinimumScore] = useState(user.minimum_score ?? 75); const [locations, setLocations] = useState(user.locations ?? ''); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('')
  const save = async () => { setSaving(true); setMessage(''); try { await onSave(user, { schedule, timezone, dailyLimit, minimumScore, locations }) } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not update rules.') } finally { setSaving(false) } }
  const remove = async () => { setSaving(true); try { await onDelete(user) } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not delete candidate.'); setSaving(false) } }
  return <div className="admin-modal-backdrop" role="presentation"><section className="admin-manager" role="dialog" aria-modal="true" aria-label={`Manage ${user.full_name}`}><header><div><small>CANDIDATE CONTROLS</small><h2>{user.full_name}</h2><p>{user.email}</p></div><button onClick={onClose} aria-label="Close candidate controls"><X /></button></header>{user.workflow_status === 'not configured' ? <div className="admin-error">This candidate has not completed setup, so there are no search rules to edit.</div> : <div className="admin-manage-grid"><label>Daily start time<input type="time" value={schedule} onChange={(event) => setSchedule(event.target.value)} /></label><label>Time zone<input value={timezone} onChange={(event) => setTimezone(event.target.value)} /></label><label>Daily job limit<input type="number" min="1" max="100" value={dailyLimit} onChange={(event) => setDailyLimit(Number(event.target.value))} /></label><label>Minimum match score<input type="number" min="50" max="100" value={minimumScore} onChange={(event) => setMinimumScore(Number(event.target.value))} /></label><label className="admin-full-width">Target locations<input value={locations} onChange={(event) => setLocations(event.target.value)} placeholder="e.g. Bengaluru, Remote" /></label></div>}{message && <div className="admin-error">{message}</div>}<footer><button className="admin-danger" disabled={saving} onClick={() => void remove()}><Trash2 /> Delete candidate</button>{user.workflow_status !== 'not configured' && <button className="admin-save" disabled={saving} onClick={() => void save()}>{saving ? 'Saving…' : 'Save search rules'}</button>}</footer></section></div>
}
